### PR TITLE
Add aggregate grade distribution GraphQL query

### PR DESCRIPTION
**Pull request by kevinzwang**

### CODE REVIEW

**Review by LEON-MING — APPROVED** [review]
sweeet. If you're confident that everything is working, let's merge this today

**Comment by g-luo** [comment]
Bumping @ageor0114

**Review by ageor0114 — APPROVED** [review]
awesome!! this is super helpful for frontend 💙

**Comment by kevinzwang** [comment]
@LEON-MING or @g-luo can you merge this in (i can't)

**Pull request merged**
